# This is a basic workflow to help you get started with Actions

name: environment_variable

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ main ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "display"
  display:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      platform: Azure
      region: central
      profile_path: profile/
      
    steps:
      - name: Display custom environment variables
        if: ${{ env.platform == 'Azure' }}
        run: |
          echo "The platform is ${{ env.platform }}"
          echo "The region is $region"
          echo "profile_path"

      - name: Display GH Default env variables
        run: |
          echo "Github Actor: $GITHUB_ACTOR"
          echo "Github Ref: $GITHUB_REF"
        
        
    
    
  
